// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProsjektOppgave_AdeleTjoennaas.Data;

#nullable disable

namespace prosjektoppgave_AdeleTjoennaas.Migrations
{
    [DbContext(typeof(CostDbContext))]
    [Migration("20260502100912_NewIntial")]
    partial class NewIntial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ProsjektOppgave_AdeleTjoennaas.Models.AzureCostCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FixedCosts")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PerMillionEventsReceived")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PerMillionEventsRetained")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAzureCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VariableCosts")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AzureCostCalculations");
                });

            modelBuilder.Entity("ProsjektOppgave_AdeleTjoennaas.Models.AzurePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArmRegionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmSkuName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveStartDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsPrimaryMeterRegion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeterName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceFamily")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TierMinimumUnits")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AzurePrices");
                });

            modelBuilder.Entity("ProsjektOppgave_AdeleTjoennaas.Models.CalculationMargin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AzureCostCalculationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerCalculationResultId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Margin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarginPercent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CalculationMargins");
                });

            modelBuilder.Entity("ProsjektOppgave_AdeleTjoennaas.Models.CustomerCalculationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveUsers")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalculationGroupId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Collector")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CollectorCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EventCost")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventsPerPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RetentionCost")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionPeriods")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UserCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomerCalculations");
                });
#pragma warning restore 612, 618
        }
    }
}
